name: Deploy main to Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build MkDocs (production)
        run: |
          mkdocs build -f mkdocs.main.yml --site-dir site
          
      - name: Deploy to gh-pages root
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          clean: true
          clean-exclude: |
            pr-preview/
          commit-message: "Deploy main: ${{ github.sha }}"
          force: false
