name: PR Previews

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build MkDocs (preview)
        run: |
          mkdocs build -f mkdocs.preview.yml --site-dir site
          
      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
