name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - "**"

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  # Single deploy job since we're just deploying
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build site
        run: mkdocs build --site-dir site
        
        
      - name: Determine destination
        id: dest
        run: |
          REF="${GITHUB_REF_NAME}"
          SAFE_REF="$(printf '%s' "$REF" \
            | sed 's,[/],-,g' \
            | tr ' ' '-' \
            | sed 's,[^A-Za-z0-9._-],-,g')"

          if [ "$REF" = "main" ]; then
            DEST="."
            URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/"
          else
            DEST="preview/${SAFE_REF}"
            URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/preview/${SAFE_REF}/"
          fi

          echo "dest=$DEST" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ needs.build.outputs.url || steps.dest.outputs.url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4